spring.config.import=optional:file:.env[.properties]

spring.application.name=customer-service
server.port=8003


#Spring Database config
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#LIMIT
MAX_LOGIN_SESSION=${MAX_LOGIN_ATTEMPT}

#Other service urls
identity_base_url=${IDENTITY_BASE_URL}