spring.config.import=optional:file:.env[.properties]

spring.application.name=MarketplaceService
server.port=8081

#Other service urls
identity_base_url=${IDENTITY_BASE_URL}
provider_base_url=${PROVIDER_BASE_URL}
customer_base_url=${CUSTOMER_BASE_URL}
master_base_url=${MATSER_BASE_URL}

